# Generated by Django 5.2 on 2025-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial=True

    dependencies=[
    ]

    operations=[
        migrations.CreateModel(
            name='MenuHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField()),
                ('dayOfWeek', models.IntegerField()),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
            ],
        ),
    ]
