# Generated by Django 5.2 on 2025-04-12 15:25

from django.db import migrations,models


class Migration(migrations.Migration):

    initial=True

    dependencies=[
    ]

    operations=[
        migrations.CreateModel(
            name='Product',
            fields=[
                ('report_id',models.CharField(max_length=255,primary_key=True,serialize=False)),
                ('status',models.CharField(default='Running',max_length=255)),
                ('file',models.FileField(blank=True,null=True,upload_to='reports/')),
            ],
        ),
    ]
