# Generated by Django 5.2 on 2025-04-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies=[
        ('report','0001_initial'),
    ]

    operations=[
        migrations.RenameModel(
            old_name='Product',
            new_name='Report',
        ),
    ]
